### ISSUE TITLE
Slicing crash with TensorFlow 0.9: Shape (?, ?) must have rank 1

### ISSUE THREAD

**Issue by spyysalo** [spyysalo/crf-test#1]
`forward.py` works with Theano on GPU but fails with TF 0.9:

```
KERAS_BACKEND=tensorflow python forward.py
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "forward.py", line 106, in <module>
    scores = forward(observations, transitions, n_steps)
  File "forward.py", line 41, in forward
    first, rest = observations[0], observations[1:]
  File "/home/smp66/env/tensorflow-0.9/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 201, in _SliceHelper
    sliced = slice(tensor, indices, sizes)
  File "/home/smp66/env/tensorflow-0.9/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 251, in slice
    return gen_array_ops._slice(input_, begin, size, name=name)
  File "/home/smp66/env/tensorflow-0.9/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1634, in _slice
    name=name)
  File "/home/smp66/env/tensorflow-0.9/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 704, in apply_op
    op_def=op_def)
  File "/home/smp66/env/tensorflow-0.9/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2262, in create_op
    set_shapes_for_outputs(ret)
  File "/home/smp66/env/tensorflow-0.9/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1702, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/smp66/env/tensorflow-0.9/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1054, in _SliceShape
    input_shape.assert_has_rank(ndims)
  File "/home/smp66/env/tensorflow-0.9/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 621, in assert_has_rank
    raise ValueError("Shape %s must have rank %d" % (self, rank))
ValueError: Shape (?, ?) must have rank 1
```

Possibly related to indexing limitations in earlier TF versions.

**Comment by spyysalo** [comment]
The issue is

```
first = observations[0]
```

where `observations` is a 2d tensor. Numpy and Theano handle this case fine (e.g. `np.zeros((2, 2))[0]`) but older TF versions appear not to fill in the missing dimensions (see e.g. http://stackoverflow.com/a/35675045).

Rewriting to the explicit

```
first = observations[0, :]
```

fixes this instance, but the same issue then shows up in another location.

Not sure if it's worth the effort to go through all partial slices and rewrite them explicitly to support older TF versions.
